/// <reference path=".snaplet/snaplet.d.ts" />
// This config was generated by Snaplet make sure to check it over before using it.
import { copycat } from "@snaplet/copycat";
import { defineConfig } from "snaplet";
copycat.setHashKey("f5mOXUMO/srNSiuP");
export default defineConfig({
  transform: {
    public: {
      User({ row }) {
        return {
          username: copycat.username(row.username),
          name: copycat.fullName(row.name),
          accountNumber: copycat.int(row.accountNumber, {
            min: 1_000_000,
            max: 10_000_000_000,
          }),
        };
      },
    },
  },
});
